const fs = require('fs');
const path = require('path');

const hiFile = path.join(__dirname, '../src/locales/hi.json');
let hiDict = {};
try { hiDict = JSON.parse(fs.readFileSync(hiFile, 'utf8')); } catch (e) {}

const translations = {
  "medisaan_voice": "MediSaaN आवाज़",
  "medisaan_bot": "MediSaaN बॉट",
  "voice": "आवाज़",
  "enter_message": "संदेश लिखें...",
  "anytime": "किसी भी समय",
  "added": "जोड़ा गया",
  "added_to_meds": "आपकी दवाइयों की सूची में जोड़ दिया गया है।",
  "removed": "हटाया गया",
  "removed_from_meds": "आपकी दवाइयों की सूची से हटा दिया गया है।",
  "report_analysis": "रिपोर्ट विश्लेषण",
  "tap_to_zoom": "ज़ूम करने के लिए टैप करें",
  "drug_interactions": "दवाओं की परस्पर क्रिया",
  "add_to_my_meds": "मेरी दवाइयों में जोड़ें",
  "remove_from_my_meds": "मेरी दवाइयों से हटाएँ",
  "test_parameters": "परीक्षण पैरामीटर",
  "parameter": "पैरामीटर",
  "status": "स्थिति",
  "next_test_when": "अगला परीक्षण कब",
  "urgent_action": "तुरंत ध्यान दें",
  "saved_to_profile": "प्रोफाइल में सहेजा गया",
  "add_to_my_record": "मेरे रिकॉर्ड में जोड़ें",
  "close": "बंद करें",
  "medicine_scans": "दवाई स्कैन",
  "report_scans": "रिपोर्ट स्कैन",
  "no_scans_found": "कोई {{type}} स्कैन नहीं मिला",
  "start_scanning": "स्कैन शुरू करें",
  "ai_doctor": "AI डॉक्टर",
  "ai_doctor_error": "AI डॉक्टर से कनेक्ट नहीं हो सका",
  "try_again": "फिर से प्रयास करें",
  "download_failed": "डाउनलोड विफल",
  "download_failed_desc": "AI मॉडल डाउनलोड करने में विफल। कृपया इंटरनेट कनेक्शन जांचें।",
  "hold_on": "रुकें",
  "download_model_first": "कृपया पहले क्लाउड आइकन पर टैप करके AI अनुवाद मॉडल डाउनलोड करें।",
  "choose_language_sub": "जारी रखने के लिए भाषा चुनें",
  "today": "आज",
  "yesterday": "कल",
  "healthy_recovery": "स्वस्थ रिकवरी!",
  "keep_following_schedule": "सर्वोत्तम परिणामों के लिए शेड्यूल का पालन करते रहें!",
  "welcome": "स्वागत है!",
  "add_medicines_to_track": "अपने स्वास्थ्य को ट्रैक करने के लिए दवाइयां जोड़ें।",
  "many_doses_missed": "कई खुराकें छूट रही हैं। रिकवरी के लिए निरंतरता महत्वपूर्ण है।",
  "almost_perfect": "लगभग सही",
  "try_not_to_miss": "और खुराक न छोड़ने का प्रयास करें। आप अच्छा कर रहे हैं!",
  "missed": "छूटी हुई",
  "taken_at": "ली गई समय:",
  "skipped_at": "छोड़ी गई समय:",
  "missed_window_closed": "छूटी (समय सीमा समाप्त)",
  "score": "स्कोर",
  "full_timeline": "पूरी टाइमलाइन",
  "no_data": "कोई डेटा नहीं",
  "logs_will_appear": "दवाइयां लेना शुरू करने पर लॉग यहां दिखाई देंगे।",
  "stop_medicine": "दवाई रोकें",
  "stop_medicine_prompt": "क्या आप रोक रहे हैं",
  "stop": "रोकें",
  "medicine_insights": "दवाई की जानकारी",
  "upcoming": "आगामी",
  "started": "शुरू की",
  "stop_confirm": "क्या आप वाकई इसे रोकना चाहते हैं",
  "delete_medicine": "दवाई मिटाएं",
  "delete_confirm": "स्थायी रूप से मिटाएं",
  "delete": "मिटाएं",
  "my_medicines": "मेरी दवाइयां",
  "no_medicines": "कोई दवाइयां नहीं जोड़ी गईं",
  "add_first_med": "नीचे दिए गए बटन पर टैप करके अपनी पहली दवाई जोड़ें।",
  "my_health": "मेरा स्वास्थ्य",
  "active": "सक्रिय",
  "med_scan_history": "दवाई स्कैन इतिहास",
  "scans": "स्कैन",
  "report_history": "रिपोर्ट इतिहास",
  "reports": "रिपोर्ट",
  "health_chat": "स्वास्थ्य चैट",
  "ask_the_bot": "बॉट से पूछें",
  "app_settings": "ऐप सेटिंग्स",
  "shortcuts_accessibility": "शॉर्टकट और एक्सेसिबिलिटी",
  "vol_shortcuts": "वॉल्यूम कुंजी शॉर्टकट",
  "vol_shortcuts_desc": "Vol↑↓ = स्कैन · Vol↑ 3s = रिपोर्ट",
  "how_to_use_shortcuts": "शॉर्टकट का उपयोग कैसे करें",
  "privacy_data": "गोपनीयता और डेटा",
  "data_storage": "डेटा स्टोरेज",
  "data_storage_desc": "सभी डेटा केवल आपके डिवाइस पर है",
  "clear": "साफ़ करें",
  "about": "के बारे में",
  "medisaan": "MediSaaN",
  "version": "संस्करण 1.0.0",
  "made_for_india": "भारत के लिए निर्मित",
  "free_no_ads": "सभी के लिए मुफ़्त · कभी कोई विज्ञापन नहीं",
  "good": "अच्छा",
  "attention": "ध्यान दें",
  "alert": "चेतावनी",
  "show_less": "कम दिखाएं",
  "view_full_consultation": "पूरा परामर्श देखें",
  "condition_insights": "स्थिति की जानकारी",
  "welcome_back": "वापसी पर स्वागत है",
  "friend": "दोस्त",
  "todays_medicine": "आज की दवाइयां",
  "progress": "प्रगति",
  "of_taken": "{{taken}} / {{total}} ली गई",
  "next_dose": "अगली खुराक",
  "health_score": "स्वास्थ्य स्कोर",
  "updated_at": "अपडेट किया गया {{time}}",
  "essential_tools": "ज़रूरी उपकरण",
  "ai_powered": "AI संचालित",
  "voice_hint": "प्रयास करें: 'हे साथी, मेरी रिपोर्ट पढ़ें'"
};

for (const key in hiDict) {
  if (translations[key]) {
    hiDict[key] = translations[key];
  } else if (hiDict[key].startsWith('[HI] ')) {
    hiDict[key] = hiDict[key].replace('[HI] ', '');
  }
}

fs.writeFileSync(hiFile, JSON.stringify(hiDict, null, 2), 'utf8');
console.log('Successfully translated hi.json!');
